language: python
cache: pip
python: 2.7.10
install:
- pip install pelican
script:
- pelican content
before_deploy:
- chmod u+x compress.sh && ./compress.sh
deploy:
  provider: s3
  access_key_id: AKIAJJUWMWYDBSKNLCDA
  secret_access_key:
    secure: KFxfEjTG9KxrSUFgL8F6EMjmS/HO2SSwDAYRaiHJgc/Eu9RvI5orNv82S9qsEGXy45bMja8SHE1YJX9joU8EUNLyIhdTzroPcm2vGMBKBsotJoDmKEx0gd0VMaQZNSx1Z3OiC99sIM3ir+mh8BkAMVxzHVR84WK3zkoNX+UTAuKa50E5yA2eLgbhPluInG5ekmPgz/ckNMawem8GdllNm0evNlVirBiKkXP5FU3zciTQroeUFAlkC2iOki9mAsbl5ENpYAnNxfV0/vJ9oH9grTvet/QpiXnMKidaHvzaMFTv/3ZJB7uZWjnMYTXyONJl2tarTycIVY7E+Gv4FreBa3ZKLvuc+9V0+vgAq6ksOOAQNDRz60Z3YQptDy8cYNmsBcEv7f5QRejySQB+bYgfEm0rFHlz17zr8TtbqWY0Y4BeB8ohV88iAVoPBf2hgXHrTyT+fsLxv/1mP3plqM0KgHyspndgaGS0tvEiMtAmfXtYu7/QXmbbl9efOHzO8SlrLx9YAU/rDAcj2JUDjBBRKFj93d+n1kH/LOYmpvZW2auWXu5CrIziElBwDwtrxhwepHhUoanaRaiZwILQHygz1hoTKCWgzDZYxzoLrcdT1uTHDorEDqVsaZK4s0QwqnlSqh5xEjVcqXt763Psvl/1N8edSNtZm5bvyMSfHL7r7Zs=
  bucket: www.town-crier.org
  region: us-east-1
  skip_cleanup: true
  default_text_charset: utf-8
  cache_control: max-age=604800
  local-dir: output
  detect_encoding: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - fanz@linux.com
    on_success: always
    on_failure: always
